# Generated by Django 5.0 on 2023-12-10 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lambda_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="matriculado",
        ),
    ]
