# Generated by Django 5.0 on 2023-12-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lambda_app", "0002_remove_aluno_matriculado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=models.CharField(max_length=14),
        ),
    ]
